// data.js
export const sliderItems = [
    {
      id: 1,
      img: "./product_images/Naruto-TeamLiquid x Naruto Kakashi Vest Female.jpg",
      title: "Naruto-TeamLiquid x Naruto Kakashi Vest Female",
      desc: "Naruto-TeamLiquid x Naruto Kakashi Vest Female",
    },
    {
      id: 2,
      img: "./product_images/Jujutsu Kaisen - Satoru Gojo Nendoroid (Tokyo Jujutsu High School Ver.)2.jpg",
      title: "Jujutsu Kaisen - Satoru Gojo Nendoroid (Tokyo Jujutsu High School Ver.)",
      desc: "Jujutsu Kaisen - Satoru Gojo Nendoroid (Tokyo Jujutsu High School Ver.)",
    },
    {
      id: 3,
      img: "./product_images/Naruto - Team Liquid x Naruto Sakura Skirt1.jpg",
      title: "Naruto - Team Liquid x Naruto Sakura Skirt",
      desc: "Naruto - Team Liquid x Naruto Sakura Skirt",
    },
  ];
  
  export const produit = [
    {
      id: 1,
      title: "Bluelock",
      image: "https://i.ibb.co/Bs0ZKpf/BLUELOCK1.webp",
      otherView:[],
      price: 0,
      desc: "Bluelock Figure",
      catagorie: "Figures",
    },
    {
      id: 2,
      title: "Zor figurine",
      image: "https://i.ibb.co/9cy5CqT/One-Piece-Resin-Statues-Figures.jpg",
      otherView:["https://i.ibb.co/H4XWMbT/Roronoa-Zorojuro-Zoro-Fan-Art-Edivaldo-Batalha.png"],
      price: 0,
      desc: "One Piece Resin Figures",
      catagorie: "Figures",
    },
    
    {
        id: 5,
        title: "Jujutsu-Kaisen-Satoru-Gojo-Nendoroid-Tokyo-Jujutsu-High-School-Ver-2",
        image: "https://i.ibb.co/HqX3Rcz/Jujutsu-Kaisen-Satoru-Gojo-Nendoroid-Tokyo-Jujutsu-High-School-Ver-4.jpg",
        price: 0,
        desc: "Bluelock Figure",
        catagorie: "Figures",
      },
      {
        id: 6,
        title: "Naruto-Team-Liquid-x-Naruto-Kakashi-Vest",
        image: "https://i.ibb.co/0jckHyP/Naruto-Team-Liquid-x-Naruto-Kakashi-Vest-Male.jpg",
        otherView:["https://i.ibb.co/wySrwsv/Naruto-Team-Liquid-x-Naruto-Kakashi-Vest-Male-Back.jpg","https://i.ibb.co/9vgSNrM/Naruto-Team-Liquid-x-Naruto-Kakashi-Vest-Female.jpg"],
        price: 0,
        desc: "Bluelock Figure",
        catagorie: "Clothing",
      },
      {
        id: 7,
        title: "Naruto-Tshirt",
        image: "https://i.ibb.co/zsZZb4J/Naruto-Tshirt5.webp",
        otherView:[],
        price: 0,
        desc: "Bluelock Figure",
        catagorie: "Clothing",
      },
      {
        id: 8,
        title: "Naruto-Tshirt",
        image: "https://i.ibb.co/nrwvRZY/Naruto-Tshirt3.webp",
        otherView:[],
        price: 0,
        desc: "Bluelock Figure",
        catagorie: "Clothing",
      },
      {
        id: 9,
        title: "Naruto-Tshirt",
        image: "https://i.ibb.co/JCcX9vN/Naruto-Tshirt2.webp",
        otherView:[],
        price: 0,
        desc: "Bluelock Figure",
        catagorie: "Clothing",
      },
      {
        id: 10,
        title: "Naruto-Shippuden-Ichiraku-Ramen-Shop-Mini-Backpack",
        image: "https://i.ibb.co/S0kRjKX/Naruto-Shippuden-Ichiraku-Ramen-Shop-Mini-Backpack1.jpg",
        otherView:[],
        price: 0,
        desc: "Bluelock Figure",
        catagorie: "Bags",
      },
      {
        id: 11,
        title: "Attack on titan style",
        image: "https://i.ibb.co/Rb7f1f3/b1467921-a5c6-4da2-aaf4-280ce49c373b.jpg",
        otherView:["https://i.ibb.co/JpM1jKS/067af3fd-e6fc-43b2-843a-4f4ba5629fcf.jpg"],
        price: 0,
        desc: "Attack on titan hood/coat",
        catagorie: "Clothing",
      },
      {
        id: 12,
        title: "Hunter-x-Hunter-Chibi-Mini-Backpack",
        image: "https://i.ibb.co/TmcXp3w/Hunter-x-Hunter-Chibi-Mini-Backpack1.jpg",
        otherView:[],
        price: 0,
        desc: "Bluelock Figure",
        catagorie: "Bags",
      },
      {
        id: 13,
        title: "Dragonball-Tshirt",
        image: "https://i.ibb.co/r5ZjpL3/Dragonball-Tshirt1.webp",
        otherView:[],
        price: 0,
        desc: "Bluelock Figure",
        catagorie: "Clothing",
      },
      {
        id: 14,
        title: "Death note backpack",
        image: "https://i.ibb.co/LZW9gNW/image.jpg",
        otherView:["https://i.ibb.co/7vQnwm5/Death-Note-Usb-Backpack-School-Bag-Laptop-Travel-Bag-Durable-Impermeable-Mochila.jpg "],
        price: 0,
        desc: "Stylish and Spacious School Bag with Double Side Pockets - Perfect for Casual Travel ",
        catagorie: "Clothing",
      },
      {
        id: 15,
        title: "Killua Zoldyck night light",
        image: "https://i.ibb.co/TBLjZQK/7.jpg",
        otherView:["https://i.ibb.co/kBkq0fs/Veilleuse-LED-en-acrylique-n-on-3-D-1.jpg" ,"https://i.ibb.co/3ftBJ4g/Killua-Zoldyck-Otaku-Lampe-Hunter-x-Hunter-Anime-Lampe-Figure-Veilleuse-16-Couleurs-rvb-Led-Distance.jpg"],
        price: 0,
        desc: "Hunter X Hunter 3D Night Lamp Bedroom Deco",
        catagorie: "Homeware",
      },
      {
        id: 16,
        title: "Tokyo Ghoul Wall art ",
        image: "https://i.ibb.co/5cVy59x/3ab52a4f-3139-461c-a587-120d949703ba.jpg",
        otherView:["https://i.ibb.co/NrPMWsT/Tokyo-Ghoul-Ken-Kaneki-6-Anime-5-Panel-Canvas-Art-Wall-Decor.jpg", "https://i.ibb.co/Z1CrhhY/26-99-US-5-Panels-Wall-Art-5-Panels-Wall-Art-Anime-Tokyo-Ghoul-Ken-Kaneki-SAO-5-Pieces-Paintings-Can.jpg"],
        price: 0,
        desc: " Ken Kaneki 5 Pieces Paintings ",
        catagorie: "Homeware",
      },
      {
        id: 17,
        title: "Dazai Osamu Throw Pillow ",
        image: "https://i.ibb.co/NSFRvLJ/14.jpg",
        otherView:["https://i.ibb.co/gzxTYXv/Dazai-Osamu-Throw-Pillow-by-milkuvvay.jpghttps://i.ibb.co/gzxTYXv/Dazai-Osamu-Throw-Pillow-by-milkuvvay.jpg" ,"https://i.ibb.co/G9d99Sc/Dazai-Osamu-Bungou-Stray-Dogs-Throw-Pillow-by-YALPOShop.jpg"],
        price: 0,
        desc: "Super soft and durable 100% spun polyester Throw pillow with double-sided print.",
        catagorie: "Homeware",
      },
      {
        id: 18,
        title: "Naruto Thermos Cup ",
        image: "https://i.ibb.co/T1ffyCK/17.jpg",
        otherView:["https://i.ibb.co/h2z5bBS/Anime-NARUTO-Uchiha-Sasuke-Cosplay-Props-Sharingan-Stainless-Steel-Water-Cup-Teens-Drink-Coffee-Ther.jpg"],
        price: 0,
        desc: " Stainless Steel Thermos Cup Originality Portable Water Bottle",
        catagorie: "Homeware",
      },
  ];
  